//! Golden cases: every hand-written log, against ProM's own answer.
//!
//! GENERATED by `tools/regolden.sh` — do not hand-edit. Regenerate after a
//! deliberate behavioural change and read the diff: every line that moves is a
//! claim that ProM's behaviour was misread before, or is being abandoned now.
//!
//! Reference: promworkbench/InductiveMiner @ de00027c (published as 6.14.5),
//! run headless with multithreading disabled — ProM's "leave out an activity"
//! fall-through races its candidates otherwise, and the reference stops being
//! reproducible against itself.

use inductive_miner_core::{discover, EventLog, Parameters, TraceVariant, Variant};
use std::collections::HashMap;

/// Activity ids follow first appearance, as they do in ProM: several tie-breaks
/// fall back on id order, so the numbering is part of the behaviour.
fn run(traces: &[&[&str]], variant: Variant, noise: f64) -> String {
    let mut ids: HashMap<&str, u32> = HashMap::new();
    let mut names: Vec<String> = Vec::new();
    let mut log = EventLog::new();
    for t in traces {
        let events = t
            .iter()
            .map(|n| {
                *ids.entry(n).or_insert_with(|| {
                    names.push(n.to_string());
                    names.len() as u32 - 1
                })
            })
            .collect();
        log.variants.push(TraceVariant { events, count: 1 });
    }
    log.collapse();
    let params = Parameters { variant, noise_threshold: noise, ..Parameters::default() };
    discover(&log, &params)
        .expect("discovery failed")
        .tree
        .render(&names, true)
}

#[test]
fn small_s1_hw_empty_log_IM() {
    assert_eq!(
        run(&[], Variant::IM, 0.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_empty_log_IMf_0_0() {
    assert_eq!(
        run(&[], Variant::IMf, 0.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_empty_log_IMf_0_01() {
    assert_eq!(
        run(&[], Variant::IMf, 0.01f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_empty_log_IMf_0_2() {
    assert_eq!(
        run(&[], Variant::IMf, 0.2f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_empty_log_IMf_0_5() {
    assert_eq!(
        run(&[], Variant::IMf, 0.5f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_empty_log_IMf_0_99() {
    assert_eq!(
        run(&[], Variant::IMf, 0.99f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_empty_log_IMf_1_0() {
    assert_eq!(
        run(&[], Variant::IMf, 1.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IM() {
    assert_eq!(
        run(&[&[]], Variant::IM, 0.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IMf_0_0() {
    assert_eq!(
        run(&[&[]], Variant::IMf, 0.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IMf_0_01() {
    assert_eq!(
        run(&[&[]], Variant::IMf, 0.01f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IMf_0_2() {
    assert_eq!(
        run(&[&[]], Variant::IMf, 0.2f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IMf_0_5() {
    assert_eq!(
        run(&[&[]], Variant::IMf, 0.5f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IMf_0_99() {
    assert_eq!(
        run(&[&[]], Variant::IMf, 0.99f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_one_empty_trace_IMf_1_0() {
    assert_eq!(
        run(&[&[]], Variant::IMf, 1.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IM() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IM, 0.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IMf_0_0() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IMf, 0.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IMf_0_01() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IMf, 0.01f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IMf_0_2() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IMf, 0.2f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IMf_0_5() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IMf, 0.5f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IMf_0_99() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IMf, 0.99f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_all_empty_IMf_1_0() {
    assert_eq!(
        run(&[&[], &[], &[]], Variant::IMf, 1.0f64),
        r"tau"
    );
}

#[test]
fn small_s1_hw_single_activity_IM() {
    assert_eq!(
        run(&[&["a"]], Variant::IM, 0.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_IMf_0_0() {
    assert_eq!(
        run(&[&["a"]], Variant::IMf, 0.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_IMf_0_01() {
    assert_eq!(
        run(&[&["a"]], Variant::IMf, 0.01f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_IMf_0_2() {
    assert_eq!(
        run(&[&["a"]], Variant::IMf, 0.2f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_IMf_0_5() {
    assert_eq!(
        run(&[&["a"]], Variant::IMf, 0.5f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_IMf_0_99() {
    assert_eq!(
        run(&[&["a"]], Variant::IMf, 0.99f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_IMf_1_0() {
    assert_eq!(
        run(&[&["a"]], Variant::IMf, 1.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IM() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IM, 0.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IMf, 0.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IMf, 0.01f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IMf, 0.2f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IMf, 0.5f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IMf, 0.99f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_activity_many_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"]], Variant::IMf, 1.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_IM() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IM, 0.0f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IMf, 0.0f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IMf, 0.01f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IMf, 0.2f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IMf, 0.5f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IMf, 0.99f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "a"]], Variant::IMf, 1.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IM() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IM, 0.0f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IMf, 0.0f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IMf, 0.01f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IMf, 0.2f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IMf, 0.5f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IMf, 0.99f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_repeated_long_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "a", "a", "a", "a"]], Variant::IMf, 1.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IM() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IM, 0.0f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IMf, 0.0f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IMf, 0.01f64),
        r"loop('a',tau)"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IMf, 0.2f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IMf, 0.5f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IMf, 0.99f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_single_mixed_lengths_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a", "a"], &["a", "a", "a"]], Variant::IMf, 1.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IM() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IM, 0.0f64),
        r"xor('a',tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IMf_0_0() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IMf, 0.0f64),
        r"xor('a',tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IMf_0_01() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IMf, 0.01f64),
        r"xor('a',tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IMf_0_2() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IMf, 0.2f64),
        r"xor('a',tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IMf_0_5() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IMf, 0.5f64),
        r"xor('a',tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IMf_0_99() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IMf, 0.99f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_IMf_1_0() {
    assert_eq!(
        run(&[&[], &["a"]], Variant::IMf, 1.0f64),
        r"'a'"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IM() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IM, 0.0f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IMf_0_0() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IMf, 0.0f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IMf_0_01() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IMf, 0.01f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IMf_0_2() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IMf, 0.2f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IMf_0_5() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IMf, 0.5f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IMf_0_99() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_empty_and_nonempty_skewed_IMf_1_0() {
    assert_eq!(
        run(&[&[], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IM() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IM, 0.0f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IMf_0_0() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IMf, 0.0f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IMf_0_01() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IMf, 0.01f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IMf_0_2() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IMf, 0.2f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IMf_0_5() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IMf, 0.5f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IMf_0_99() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_mostly_empty_IMf_1_0() {
    assert_eq!(
        run(&[&[], &[], &[], &[], &[], &[], &[], &[], &[], &["a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IM() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IM, 0.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IMf, 0.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IMf, 0.01f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IMf, 0.2f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IMf, 0.5f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq2_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_seq3_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IM, 0.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq3_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq3_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.01f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq3_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq3_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq3_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq3_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IM, 0.0f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.0f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.01f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.2f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.5f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq_optional_middle_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IM, 0.0f64),
        r"seq(xor(seq('a','b'),tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IMf, 0.0f64),
        r"seq(xor(seq('a','b'),tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IMf, 0.01f64),
        r"seq(xor(seq('a','b'),tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IMf, 0.2f64),
        r"seq(xor(seq('a','b'),tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IMf, 0.5f64),
        r"seq(xor(seq('a','b'),tau),'c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq_pivot_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_seq_long_IM() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IM, 0.0f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_seq_long_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IMf, 0.0f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_seq_long_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IMf, 0.01f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_seq_long_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_seq_long_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_seq_long_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_seq_long_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c','d','e','f','g')"
    );
}

#[test]
fn small_s1_hw_xor2_IM() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IM, 0.0f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor2_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IMf, 0.0f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor2_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IMf, 0.01f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor2_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IMf, 0.2f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor2_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IMf, 0.5f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor2_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IMf, 0.99f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor2_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["b"]], Variant::IMf, 1.0f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor3_IM() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IM, 0.0f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor3_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IMf, 0.0f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor3_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IMf, 0.01f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor3_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IMf, 0.2f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor3_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IMf, 0.5f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor3_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IMf, 0.99f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor3_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["b"], &["c"]], Variant::IMf, 1.0f64),
        r"xor('a','b','c')"
    );
}

#[test]
fn small_s1_hw_xor_branches_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IM, 0.0f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_branches_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IMf, 0.0f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_branches_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IMf, 0.01f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_branches_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IMf, 0.2f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_branches_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IMf, 0.5f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_branches_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IMf, 0.99f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_branches_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["c", "d"]], Variant::IMf, 1.0f64),
        r"xor(seq('a','b'),seq('c','d'))"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IM() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IM, 0.0f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IMf, 0.0f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IMf, 0.01f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IMf, 0.2f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IMf, 0.5f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IMf, 0.99f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_xor_skewed_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["a"], &["b"]], Variant::IMf, 1.0f64),
        r"xor('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IM, 0.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IMf, 0.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IMf, 0.01f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IMf, 0.2f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IMf, 0.5f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IMf, 0.99f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par2_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"]], Variant::IMf, 1.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par3_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IM, 0.0f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par3_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IMf, 0.0f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par3_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IMf, 0.01f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par3_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IMf, 0.2f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par3_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IMf, 0.5f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par3_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IMf, 0.99f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par3_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"], &["b", "a", "c"], &["b", "c", "a"], &["c", "a", "b"], &["c", "b", "a"]], Variant::IMf, 1.0f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_par_partial_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IM, 0.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_partial_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IMf, 0.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_partial_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IMf, 0.01f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_partial_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IMf, 0.2f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_partial_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IMf, 0.5f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_partial_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IMf, 0.99f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_partial_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["a", "b"]], Variant::IMf, 1.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_par_nested_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IM, 0.0f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_par_nested_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IMf, 0.0f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_par_nested_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IMf, 0.01f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_par_nested_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IMf, 0.2f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_par_nested_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IMf, 0.5f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_par_nested_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IMf, 0.99f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_par_nested_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "c", "b"]], Variant::IMf, 1.0f64),
        r"seq('a',and('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_simple_IM() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IM, 0.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_simple_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IMf, 0.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_simple_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IMf, 0.01f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_simple_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IMf, 0.2f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_simple_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IMf, 0.5f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_simple_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IMf, 0.99f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_simple_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"]], Variant::IMf, 1.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IM() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IM, 0.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IMf, 0.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IMf, 0.01f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IMf, 0.2f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IMf, 0.5f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IMf, 0.99f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_twice_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "b", "a", "b", "a"]], Variant::IMf, 1.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IM, 0.0f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IMf, 0.0f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IMf, 0.01f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IMf, 0.2f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IMf, 0.5f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IMf, 0.99f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_body_seq_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "c", "a", "b"]], Variant::IMf, 1.0f64),
        r"loop(seq('a','b'),'c')"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IM() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IM, 0.0f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IMf, 0.0f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IMf, 0.01f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IMf, 0.2f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IMf, 0.5f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IMf, 0.99f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_two_redos_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "a"], &["a", "c", "a"]], Variant::IMf, 1.0f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IM() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IM, 0.0f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IMf_0_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IMf, 0.0f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IMf_0_01() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IMf, 0.01f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IMf_0_2() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IMf, 0.2f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IMf_0_5() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IMf, 0.5f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IMf_0_99() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IMf, 0.99f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_redo_seq_IMf_1_0() {
    assert_eq!(
        run(&[&["a"], &["a", "b", "c", "a"]], Variant::IMf, 1.0f64),
        r"loop('a',seq('b','c'))"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IM() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IM, 0.0f64),
        r"and(loop('a',tau),loop('b',tau))"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IMf, 0.0f64),
        r"and(loop('a',tau),loop('b',tau))"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IMf, 0.01f64),
        r"and(loop('a',tau),loop('b',tau))"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IMf, 0.2f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IMf, 0.5f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IMf, 0.99f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_loop_vs_parallel_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "a"], &["b", "a", "b"]], Variant::IMf, 1.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IM() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IM, 0.0f64),
        r"seq('a',loop('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.0f64),
        r"seq('a',loop('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.01f64),
        r"seq('a',loop('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_self_loop_in_seq_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "b", "c"], &["a", "b", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IM() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IM, 0.0f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IMf, 0.0f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IMf, 0.01f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IMf, 0.2f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IMf, 0.5f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IMf, 0.99f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_xor_in_seq_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "e"]], Variant::IMf, 1.0f64),
        r"seq('a',xor('b','c'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IM, 0.0f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IMf, 0.0f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IMf, 0.01f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IMf, 0.2f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IMf, 0.5f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IMf, 0.99f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_par_in_xor_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["b", "a"], &["c"]], Variant::IMf, 1.0f64),
        r"xor('c',and('a','b'))"
    );
}

#[test]
fn small_s1_hw_nested_deep_IM() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IM, 0.0f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_deep_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IMf, 0.0f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_deep_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IMf, 0.01f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_deep_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IMf, 0.2f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_deep_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IMf, 0.5f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_deep_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IMf, 0.99f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_deep_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "e"], &["a", "c", "d", "e"], &["a", "d", "c", "e"]], Variant::IMf, 1.0f64),
        r"seq('a',xor('b',and('c','d')),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IM() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IM, 0.0f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IMf_0_0() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IMf, 0.0f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IMf_0_01() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IMf, 0.01f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IMf_0_2() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IMf, 0.2f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IMf_0_5() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IMf, 0.5f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IMf_0_99() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IMf, 0.99f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_nested_loop_in_seq_IMf_1_0() {
    assert_eq!(
        run(&[&["s", "a", "e"], &["s", "a", "b", "a", "e"]], Variant::IMf, 1.0f64),
        r"seq('s',loop('a','b'),'e')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IM, 0.0f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IMf, 0.0f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IMf, 0.01f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IMf, 0.2f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IMf, 0.5f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IMf, 0.99f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_flower_ish_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["c", "b", "a"], &["b", "a", "c"], &["a", "c", "b"], &["b", "c", "a"]], Variant::IMf, 1.0f64),
        r"and('a','b','c')"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IM() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IM, 0.0f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IMf_0_0() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IMf, 0.0f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IMf_0_01() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IMf, 0.01f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IMf_0_2() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IMf, 0.2f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IMf_0_5() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IMf, 0.5f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IMf_0_99() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IMf, 0.99f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_once_per_trace_IMf_1_0() {
    assert_eq!(
        run(&[&["x", "a", "b"], &["a", "x", "b"], &["a", "b", "x"]], Variant::IMf, 1.0f64),
        r"and('x',seq('a','b'))"
    );
}

#[test]
fn small_s1_hw_tau_loop_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IM, 0.0f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IMf, 0.0f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IMf, 0.01f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IMf, 0.2f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IMf, 0.5f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_tau_loop_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b", "a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IM() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IM, 0.0f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IMf, 0.0f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IMf, 0.01f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IMf, 0.2f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IMf, 0.5f64),
        r"loop(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_tau_loop_strict_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "a", "b"], &["a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IM() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IM, 0.0f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IMf, 0.0f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IMf, 0.01f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IMf, 0.2f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IMf, 0.5f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IMf, 0.99f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_duplicate_heavy_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "a", "c", "a"], &["a", "c", "a", "b", "a"]], Variant::IMf, 1.0f64),
        r"loop('a',xor('b','c'))"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IM, 0.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IMf, 0.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IMf, 0.01f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IMf, 0.2f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IMf, 0.5f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IMf, 0.99f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_reversal_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["b", "a"]], Variant::IMf, 1.0f64),
        r"and('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IM, 0.0f64),
        r"seq('a',xor('x',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IMf, 0.0f64),
        r"seq('a',xor('x',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IMf, 0.01f64),
        r"seq('a',xor('x',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IMf, 0.2f64),
        r"seq('a',xor('x',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IMf, 0.5f64),
        r"seq('a',xor('x',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','x','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_extra_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "x", "b", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','x','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IM, 0.0f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.0f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.01f64),
        r"seq('a',xor('b',tau),'c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_skip_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_empty_IM() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IM, 0.0f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_rare_empty_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IMf, 0.0f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_rare_empty_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IMf, 0.01f64),
        r"xor(seq('a','b'),tau)"
    );
}

#[test]
fn small_s1_hw_rare_empty_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IMf, 0.2f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_empty_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IMf, 0.5f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_empty_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_empty_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &["a", "b"], &[]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_rare_start_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IM, 0.0f64),
        r"seq(xor('a',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_start_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IMf, 0.0f64),
        r"seq(xor('a',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_start_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IMf, 0.01f64),
        r"seq(xor('a',tau),'b','c')"
    );
}

#[test]
fn small_s1_hw_rare_start_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_start_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_start_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_start_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_end_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IM, 0.0f64),
        r"seq('a','b',xor('c',tau))"
    );
}

#[test]
fn small_s1_hw_rare_end_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IMf, 0.0f64),
        r"seq('a','b',xor('c',tau))"
    );
}

#[test]
fn small_s1_hw_rare_end_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IMf, 0.01f64),
        r"seq('a','b',xor('c',tau))"
    );
}

#[test]
fn small_s1_hw_rare_end_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_end_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_end_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_rare_end_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_two_rare_IM() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IM, 0.0f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_two_rare_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IMf, 0.0f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_two_rare_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IMf, 0.01f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_two_rare_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IMf, 0.2f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_two_rare_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IMf, 0.5f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_two_rare_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IMf, 0.99f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_two_rare_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["a", "b", "c"], &["b", "a", "c"], &["a", "c", "b"]], Variant::IMf, 1.0f64),
        r"and('b',seq('a','c'))"
    );
}

#[test]
fn small_s1_hw_all_lengths_IM() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IM, 0.0f64),
        r"xor(seq('a',xor('b',tau),xor('c',tau)),tau)"
    );
}

#[test]
fn small_s1_hw_all_lengths_IMf_0_0() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IMf, 0.0f64),
        r"xor(seq('a',xor('b',tau),xor('c',tau)),tau)"
    );
}

#[test]
fn small_s1_hw_all_lengths_IMf_0_01() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IMf, 0.01f64),
        r"xor(seq('a',xor('b',tau),xor('c',tau)),tau)"
    );
}

#[test]
fn small_s1_hw_all_lengths_IMf_0_2() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IMf, 0.2f64),
        r"xor(seq('a',xor('b',tau),xor('c',tau)),tau)"
    );
}

#[test]
fn small_s1_hw_all_lengths_IMf_0_5() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IMf, 0.5f64),
        r"seq('a','b',xor('c',tau))"
    );
}

#[test]
fn small_s1_hw_all_lengths_IMf_0_99() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_all_lengths_IMf_1_0() {
    assert_eq!(
        run(&[&[], &["a"], &["a", "b"], &["a", "b", "c"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c')"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IM() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IM, 0.0f64),
        r"seq(loop('a',tau),loop('b',tau))"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IMf, 0.0f64),
        r"seq(loop('a',tau),loop('b',tau))"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IMf, 0.01f64),
        r"seq(loop('a',tau),loop('b',tau))"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IMf, 0.2f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IMf, 0.5f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IMf, 0.99f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_repeats_in_trace_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "a", "b", "b"], &["a", "b"]], Variant::IMf, 1.0f64),
        r"seq('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IM() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IM, 0.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IMf, 0.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IMf, 0.01f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IMf, 0.2f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IMf, 0.5f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IMf, 0.99f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_interleaved_repeat_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "a", "b", "a"]], Variant::IMf, 1.0f64),
        r"loop('a','b')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IM() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IM, 0.0f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IMf, 0.0f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IMf, 0.01f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IMf, 0.2f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IMf, 0.5f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IMf, 0.99f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_alphabet_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"]], Variant::IMf, 1.0f64),
        r"seq('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p')"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IM() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IM, 0.0f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IMf_0_0() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IMf, 0.0f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IMf_0_01() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IMf, 0.01f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IMf_0_2() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IMf, 0.2f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IMf_0_5() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IMf, 0.5f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IMf_0_99() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IMf, 0.99f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

#[test]
fn small_s1_hw_wide_shuffled_IMf_1_0() {
    assert_eq!(
        run(&[&["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p"], &["p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]], Variant::IMf, 1.0f64),
        r"and('d','e','f','g','h','i','j','k','l','m','n','o','p',loop(xor('a','c'),'b'))"
    );
}

