#!/usr/bin/env python3
"""Turns oracle output into a Rust golden-test file. Driven by tools/regolden.sh."""
import json
import sys

HEADER = '''//! Golden cases: every hand-written log, against ProM's own answer.
//!
//! GENERATED by `tools/regolden.sh` — do not hand-edit. Regenerate after a
//! deliberate behavioural change and read the diff: every line that moves is a
//! claim that ProM's behaviour was misread before, or is being abandoned now.
//!
//! Reference: promworkbench/InductiveMiner @ de00027c (published as 6.14.5),
//! run headless with multithreading disabled — ProM's "leave out an activity"
//! fall-through races its candidates otherwise, and the reference stops being
//! reproducible against itself.

use inductive_miner_core::{discover, EventLog, Parameters, TraceVariant, Variant};
use std::collections::HashMap;

/// Activity ids follow first appearance, as they do in ProM: several tie-breaks
/// fall back on id order, so the numbering is part of the behaviour.
fn run(traces: &[&[&str]], variant: Variant, noise: f64) -> String {
    let mut ids: HashMap<&str, u32> = HashMap::new();
    let mut names: Vec<String> = Vec::new();
    let mut log = EventLog::new();
    for t in traces {
        let events = t
            .iter()
            .map(|n| {
                *ids.entry(n).or_insert_with(|| {
                    names.push(n.to_string());
                    names.len() as u32 - 1
                })
            })
            .collect();
        log.variants.push(TraceVariant { events, count: 1 });
    }
    log.collapse();
    let params = Parameters { variant, noise_threshold: noise, ..Parameters::default() };
    discover(&log, &params)
        .expect("discovery failed")
        .tree
        .render(&names, true)
}
'''


def rs_traces(traces):
    inner = ", ".join(
        "&[" + ", ".join(f'"{e}"' for e in t) + "]" for t in traces
    )
    return f"&[{inner}]"


def main():
    cases = {}
    for line in open(sys.argv[1]):
        if line.strip():
            c = json.loads(line)
            cases[c["id"]] = c
    prom = {}
    for line in open(sys.argv[2]):
        if line.strip():
            r = json.loads(line)
            prom[r.get("id")] = r

    print(HEADER)
    seen = set()
    for cid, c in cases.items():
        p = prom.get(cid)
        if not p or "canonical" not in p:
            continue
        name = "".join(ch if ch.isalnum() else "_" for ch in cid)
        if name in seen:
            continue
        seen.add(name)
        variant = "Variant::IM" if c.get("variant") == "IM" else "Variant::IMf"
        noise = c.get("noiseThreshold", 0.0)
        print("#[test]")
        print(f"fn {name}() {{")
        print(f"    assert_eq!(")
        print(f"        run({rs_traces(c['traces'])}, {variant}, {noise}f64),")
        print(f'        r"{p["canonical"]}"')
        print("    );")
        print("}")
        print()


if __name__ == "__main__":
    main()
